### ISSUE TITLE
case insensitive query of synsets

### ISSUE THREAD

**Issue by engintekin** [goodmami/wn#114]
Hello, thank you for this library. I love using it.
Is there a way to query synsets in a case insensitive way?

For example: 
```python
wn.synsets("Rubicon")
[Synset('ewn-08662127-n'), Synset('ewn-05757039-n')]

wn.synsets("rubicon")
[] 
```

**Comment by goodmami** [comment]
Hi, thanks for the kind words!

This is indeed a missing feature but I put in some preliminary support in the v0.6 release. The database now contains normalized forms which are not only case-normalized but also removes accents (e.g., *pequeño* becomes *pequeno* in Spanish). The next step is hooking up the search so calls like `wn.synsets()` use the normalized form. I haven't yet decided on the API, though, like how to turn normalized search off, or how it works with the planned support for morphological analysis, etc.

Issue #105 is tracking this feature.

**Comment by goodmami** [comment]
I'm going to close this issue. Please subscribe to #105 if you wish to track the feature.
