### ISSUE TITLE
When is 0.8.0 expected to be released

### ISSUE THREAD

**Issue by vsraptor** [goodmami/wn#127]
i'm anticipating the new Similarity measures ;) ...

**Comment by goodmami** [comment]
When it's done? :grin: 

Unfortunately, Wn isn't my priority this month so progress has been a bit slow. I have pushed what I have been working on to the v0.8.0 branch and opened a PR (#128), so feel free to take a look. I think all of the issues in the [milestone](https://github.com/goodmami/wn/milestone/5) have been accomplished, but mainly what's missing now is tests for the new similarity metrics.

As usual, PRs are welcome.
