### ISSUE TITLE
add a check function

### ISSUE THREAD

**Issue by fcbond** [goodmami/wn#143]
I would like to add a module (check.py) that checks for various issues with a wordnet.  The goal is to help developers avoid producing wordnets with structural problems.  It would duplicate some of the functionality of the `validate.py` in the 
https://github.com/globalwordnet/english-wordnet/ and the checks of the https://github.com/globalwordnet/OMW but make them more widely available.

**Comment by goodmami** [comment]
I would have been hesitant, initially, as this kind of operation is probably only useful for wordnet authors, but there have been many easy-to-detect-if-you-know-what-to-look-for kind of issues with some wordnets of late, so it makes sense to make the tests easy to run. It would be useful if each test could be run individually. It would also be useful if the tests could be run from the command line.

Here's an initial list of tests:
- Every lexical entry has at least 1 sense
- Every synset has at least 1 member
- Synsets should have the same POS as their members (but `s` on a synset implies `a` on the member)
- Synsets should have the same POS as their hypernyms
- Inverse relations are present (e.g., hypernym/hyponym)
- Each ILI is assigned to at most one synset in a lexicon

Some simple things are already checked by `wn.lmf` or when adding a lexicon to the database:
- POS values are within `n`, `v`, `a`, `r`, and `s` (currently a warning is issued when reading the XML file)
- IDs are unique (sqite3 raises an integrity error on the uniqueness violation)
- Relation names are valid (currently `wn.lmr` throws an error if not)

Some things are not checked at this level but should be:
- POS on Lemma should not include `s`

Feel free to add more checks.

**Comment by goodmami** [comment]
@fcbond would this be better as an operation over WN-LMF files or in-database lexicons? The benefit of working on the XML files is that we can write the checks for things that the database would refuse to load, such as missing relation targets, repeated IDs, etc. The benefit of working with in-database lexicons is that the features of Wn become available for the checks and the whole lexicon wouldn't have to be held in memory at once. The runtimes are probably similar: in-memory would start faster, but in-file would (probably) be quicker to run.

I'm leaning slightly towards checking the files, but I welcome your thoughts.

**Comment by goodmami** [comment]
To be clear, the v0.9.0 branch is not yet released. When it's merged into the main branch I'll create the v0.9.0 release.

**Comment by goodmami** [comment]
After recent discussions I'm starting to have a nagging idea that this should be a separate package. There are some benefits:
* Wn is leaner for normal users
* omw-data can use it for validation without waiting for Wn 0.9.0 (a one-time benefit)
* Dependencies like NetworkX can be added without complications
