### ISSUE TITLE
Documentation of the various English wordnets

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#153]
In the upcoming release there are now 5 English wordnet projects:

* `oewn`
* `ewn` (2 versions)
* `omw-en`
* `omw-en31`
* `own-en`

These will need some explanation so users know which one to get. In addition there may be some issues, publications, or documentation using the `pwn` identifier, which was delisted in favor of `omw-en` and `omw-en31`.

Something like this:

> The **Open English Wordnet** (`oewn`) is recommended for most work with English data, as it is the most advanced and actively developed project. The **OMW English Wordnet based on WordNet 3.0** (`omw-en`) is recommended in conjunction with the other OMW wordnets, or when strict compatibility with the Princeton WordNet 3.0 is needed. Similarly, the **OMW English Wordnet based on WordNet 3.1**  is recommended when compatibility with the Princeton WordNet 3.1 is needed. The **Open Wordnet of English** (`own-en`) is recommended for use in conjunction with the **Open Wordnet of Portuguese** (`own-pt`).

**Comment by arademaker** [comment]
That is a good starting point. I agree that we need to make clear for the users. Hope that differences will be reduced in the future and some of those resources will be eventually merged.
