### ISSUE TITLE
SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by Vosloo** [goodmami/wn#180]
**Problem description**

Hello, I am trying to create a micro-service (with Flask) that use the library for getting synsets of a given word. I've noticed some unexpected behaviour when creating quering for synsets and Flask. For the attached code below I am getting an error: 
```console
ProgrammingError('SQLite objects created in a thread can only be used in that same thread.
The object was created in thread id 139815518537536 and this is thread id 139811777947392.
```

**Code to reproduce**

```python
# foo.py
import wn
from wn.morphy import Morphy

class Foo:
    def __init__(self):
        self.wnde, self.morphy = self._initialize_wn()

    def _initialize_wn(self) -> tuple[wn.Wordnet, Morphy]:
        print("Initializing Wordnet...")
        wn.download("odenet")

        wnde = wn.Wordnet(lang="de")
        morphy = Morphy(wnde)
        wnde.lemmatizer = morphy

        return wnde, morphy

    def get_synsets(self, word: str) -> list:
        return self.wnde.synsets(word)
```

```python
from flask import Flask
from foo import Foo

app = Flask(__name__)
foo = Foo()

@app.route("/", methods=["POST])
def do_stuff():
    word = request.form["data"]
    return {"data": foo.generate(word)}, 200

if __name__ == "__main__":
    app.run(
        threaded=True,  # Doesn't matter here if True or False, error still present
        host="0.0.0.0",
        debug=True,
    )
```

**Expected behavior**

We should get a list of synsets.

**Environment**

 - Python 3.10.5
 - Wn 0.9.3
 - Lexicons:
  -- odenet 1.4 [de] Offenes Deutsches WordNet (only using this one)
  -- oewn 2021 [en] Open English WordNet

**Comment by goodmami** [comment]
@Vosloo thanks for the detailed report. SQLite doesn't allow multithreading by default. Have you tried using the [wn.config.allow_multithreading](https://wn.readthedocs.io/en/latest/api/wn.html?highlight=thread#wn._config.WNConfig.allow_multithreading) option?

```python
import wn
wn.config.allow_multithreading = True
```

Also see https://github.com/goodmami/wn/issues/86.

**Comment by goodmami** [comment]
I'm going to close this, but feel free to reopen if my suggestion above doesn't work. I tried it using your code to reproduce the issue (which BTW wasn't usable without a few fixes) and I got around the `ProgrammingError`, so I'll assume that this fixes the problem.

**Comment by Vosloo** [comment]
I wasn't aware of such an option and it does indeed work, thank You!
