### ISSUE TITLE
Add OEWN 2022 to index

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#181]
The [OEWN 2022](https://github.com/globalwordnet/english-wordnet/releases/tag/2022-edition) version is released and it should be tested to ensure compatibility and added to the index in the next version of Wn.

**Additional context**

This release now has an asset on the GitHub release (see https://github.com/globalwordnet/english-wordnet/issues/764#event-8132914897), so that can be added as a mirror in addition to the https://en-word.net/ hosted version.

**Comment by ekaf** [comment]
The following recent commit in OEWN seems likely to cause a compatibility problem, unless Wn also updates its ILI: 
_Add updated ILI codes from @arademaker #891_ (
https://github.com/globalwordnet/english-wordnet/pull/891/commits/1e7f3817ad4cdfbf6953de4543ad92c4ef527f87)

**Comment by goodmami** [comment]
Thanks, @ekaf. CILI could really use a new release, but it also needs a procedure for creating releases (https://github.com/globalwordnet/cili/issues/4, https://github.com/globalwordnet/cili/issues/9), so that may not happen soon. Just having missing ILIs is not a huge issue, because it will be treated as when the CILI resource is not loaded (status is `presupposed` and ILI definitions are not available).
