### ISSUE TITLE
Add a `conda` install option for `wn` on conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [goodmami/wn#184]
A conda installation option from `conda-forge` channel could be very helpful for all downstream packages that depend on `wn`. I have already started working on this, to add `wn` to conda-forge.

Conda-forge PR: 

- https://github.com/conda-forge/staged-recipes/pull/22525

Once the conda-forge PR is merged, you will be able to install the library with conda as follows:

```sh
conda install -c conda-forge wn
```

:bulb: I will push a PR to update the docs once the package is available on conda-forge.

**Comment by sugatoray** [comment]
cc: @goodmami Could you please assign this issue to me, since I am already working on this?

**Comment by goodmami** [comment]
Hi @sugatoray, thanks for helping out! I don't use normally use conda and I don't know what is required for publishing on conda-forge. It looks like no code or packaging changes are required in this repository but I see you've offered to update the docs, which would be welcome.

Will subsequent Wn releases need to be generate a corresponding PR to update the version in conda-forge? If so, maybe I could ask you to subscribe to releases so you could do that? Or maybe it could be done automatically with a GitHub Action?

**Comment by sugatoray** [comment]
Conda-forge packages are maintained from GitHub repositories, typically called "feedstocks". 

Once you publish a new version on PyPI, you can then update the package recipe on the feedstock for the latest version. However, often a conda-forge bot will automatically pick up the new version from pypi and start the PR to update it. 

If it's okay with you, I would suggest at least one of the core developers of `wn` be involved in co-maintaining the package recipe with me on the feedstock repository. 

The feedstock repository will be created once the PR is approved.

**Comment by goodmami** [comment]
> [...] a conda-forge bot will automatically pick up the new version from pypi and start the PR to update it.

I have now released 0.9.4 of Wn, so I should expect to see a PR pop up here? https://github.com/conda-forge/staged-recipes/pulls

> If it's okay with you, I would suggest at least one of the core developers of wn be involved in co-maintaining the package recipe with me on the feedstock repository.

I'm happy to be reactive here, like answering questions or approving changes, but I'm not keen to take on additional proactive responsibilities. If the PRs are generated automatically and I get notified, that shouldn't be much of a problem.

If all is good otherwise, I think we can close this issue once a PR to update the docs is merged. At a minimum, I think this would add some instructions to the setup doc: https://wn.readthedocs.io/en/latest/setup.html

**Comment by sugatoray** [comment]
The feedstock repository is here (not conda-forge/staged-recipes):

- https://github.com/onda-forge/wn-feedstock
