### ISSUE TITLE
Move packaging to Hatch

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#201]
In some other projects of mine, I've moved to [Hatch](https://hatch.pypa.io/1.12/) for packaging and have really enjoyed it. While flit has been great, having one tool handle packaging, CI scripts, virtual environments, etc., is quite useful.

**Comment by arademaker** [comment]
Nice, how this change affects the users and developers?

**Comment by goodmami** [comment]
Nothing changes for users. It should make life easier for developers. You can see what I mean in [Penman's developer docs](https://penman.readthedocs.io/en/latest/setup.html#for-contributors) where I also switched to Hatch.
