### ISSUE TITLE
Add OEWN 2024 to index

### ISSUE THREAD

**Issue by rayza** [goodmami/wn#221]
The 2024 edition of the Open English Wordnet has been released: https://github.com/globalwordnet/english-wordnet/releases/tag/2024-edition

**Comment by goodmami** [comment]
Thanks! I was waiting until some issues were fixed before adding OEWN 2024:

- https://github.com/goodmami/wn/issues/215
- https://github.com/goodmami/wn/issues/213
- https://github.com/goodmami/wn/issues/216

The first two are done but I don't have a good solution for the last one yet. They aren't strictly necessary to be able to use OEWN 2024 for most purposes, but the last one is necessary for people wanting to make use of the `other` relations.
