### ISSUE TITLE
Add progress bar for lmf.load()

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#46]
Sometimes loading the XML file can be slow, so it would be nice to have a progress bar for this step as well.

**Comment by dpalmasan** [comment]
Hello, thanks for this project, it looks interesting. I can lend you a hand with this issue, already submitted a PR, hope you don't mind.

Cheers

**Comment by goodmami** [comment]
Great, thanks! I have some comments so I'll put those in the PR.
