### ISSUE TITLE
Function to list available projects

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#60]
The `wn.lexicons()` lists lexicons that are installed, and the indexed projects are in `wn.config` but there is not a public API way of showing the projects that are available. Some options:

1. Add some `wn.config.list_projects()` function that is like `wn.config.get_project_info()` but it lists all, not just one.

2. Add a top level `wn.projects()` which does about the same thing as (1), but is more visible.

3. Make `wn.config._index` publicly available as `wn.config.index` so users can inspect the mapping directly.

Note that we can't just add a `installed=None` default parameter to `wn.lexicons()` because the index doesn't contain info about lexicons but about projects (a project may contain multiple lexicons, like `omw` does).

**Comment by fcbond** [comment]
I like option 2

**Comment by goodmami** [comment]
I'm thinking option (3) and maybe also (2). One thing that it will be hard to do is show whether a project is installed or not, because once they go into the database, it's not the project IDs but the lexicon IDs that are stored.

This brings up a second issue, which is that `wn.remove()` removes lexicons while `wn.add()` and `wn.download()` get projects. So once we do `wn.download('omw')` we cannot do `wn.remove('omw')` but instead must remove each OMW lexicon individually. If I store a table mapping installed project IDs to lexicon IDs, then we could remove a project and allow something like `wn.projects()` to show whether or not something is installed.

**Comment by goodmami** [comment]
One more thing: I also prefer option (2) to (1) because the config module does not have access to the DB so even if I change the database as described in my previous comment, the `wn.config.list_projects()` still would not be able to query if something is installed.
