### ISSUE TITLE
Why does building the database take so long?

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#69]
In #67 @fushinari asked:

> Why does the building of the database take so long? Is there any way to speed it up? It took more than an hour for building the ewn database in my case. That seems way too long for normal use. An easy way out seems to be to simple redistribute the `wn.db` file but I'd like to avoid that.

An hour? For me downloading and building EWN takes roughly 45 seconds. To be certain, it's longer than with the old library for two reasons: (1) the file to download was smaller (WN-LMF vs WNDB formats) and (2) the old library read the from the files each time. Also see this [FAQ](https://wn.readthedocs.io/en/latest/faq.html#why-does-wn-s-database-get-so-big) about Wn's database size. Do you know if it was downloading or building that took all that time?

And I'm not sure if there's much more I can do about speeding up the building part as I've already spent some time optimizing it, but I'm not an SQL expert so I'm happy to receive suggestions. I could speed up the XML reading part by using a different parser, but that wouldn't make a big dent in the overall building time.

I agree that I would not want to distribute the `wn.db` file.

**Comment by fushinari** [comment]
Downloading was quite fast. But building was what took up the rest of the hour. I'm on an HDD in case that matters.

**Comment by goodmami** [comment]
Yes, I was afraid it'd be an HDD thing as I'm on SSD. If that's the reason, then it'll be hard to test.

**Comment by fushinari** [comment]
No worries, I'll experiment with this when I get time.

**Comment by goodmami** [comment]
It might be worth trying to turn some sqlite knobs which didn't help me much, but might help those on HDD. From https://stackoverflow.com/q/1711631/1441112. Basically it's just these two things:

```sql
PRAGMA synchronous = OFF
PRAGMA journal_mode = MEMORY
```

Python's sqlite3 module already manages transactions, and it's not feasible to build the indexes after the inserts because the database isn't just built once. The `synchronous` setting is the biggest win, according to the linked SO question, and I think we can live with the risk of a corrupt database if the system crashes (it's not *that* big a deal to rebuild it).

**Comment by goodmami** [comment]
@fushinari the changes described above are now released in v0.3.0. When you get a chance, I'd appreciate you letting me know if it improves the build time at all.

**Comment by fushinari** [comment]
I just tested and I'm sorry to report that I got to see no improvement on my system :(

**Comment by goodmami** [comment]
Thanks for testing, even if the result was disappointing. I guess I have to look elsewhere for optimizations.

**Comment by goodmami** [comment]
There might be some other issue on your end. A friend gave the idea that I could use an external HDD for testing, and when I do that i get it taking about 2x as long (roughly a minute) to install PWN 3.0. But nowhere near an hour.

**Comment by fushinari** [comment]
I finally have a few days free, so I'll be testing it in more detail through the next few days and if possible, fixing it. If it's somehow impossible to fix, I will offer the option of downloading the pre-built database. So no worries. :)

**Comment by fushinari** [comment]
Well... this is awkward... Now, it takes about 5-6 minutes but not longer for me. So I'm really confused as to why this was happening in the first place... I think it's safe to close this. If I ever encounter it again or I find ways to improve it, I'll let you know. Thanks for being so responsive.

Btw, I've gotten Wordbook working with the new callback method and it seems to be working fine but I'm also in the middle of switching the build system, removing the Qt5 UI, etc. So, I'll only get to test it properly a bit later.

**Comment by goodmami** [comment]
Ok, glad to hear that! I agree about closing the issue. It sounds like maybe you had something else using the disk at the same time (background indexing, antivirus, etc.) on the first runs. 5-6 minutes is still longer than I'd like, but it's not obscene like an hour would be.

Please open another issue if you have any other issues.

**Comment by fushinari** [comment]
I made an interesting discovery. When my application runs the build process, it takes a minute or even less. But when running the same process through a terminal, it takes 5-6 minutes. Luckily for me, the first one is my actual use case, so everything looks fine.

**Comment by goodmami** [comment]
Hmm, printing inside loops does slow down things quite a bit. The progress bar only prints every 1k inserts, and there are roughly 1.3m inserts for the English WordNet 2020, so that's about 1.3k prints during the add. That alone should not cause 5 minutes of additional time, unless you were printing other things, too. If you were capturing stdout in a pipe or something it might have deadlocked.

But anyway, thanks for your continued investigations. If you find something concrete that could be improved I'd like to hear about it. Otherwise I'll consider this issue resolved.
