### ISSUE TITLE
Lexicon extensions in the database

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#99]
The LMF 1.1 changes in #7 will allow lexicon extensions, which are lexicons that build on top of others. This issue is related to the database changes required to support them.

* ~Base lexicons should not be required to be installed, so foreign keys to the base lexicon should be nullable.~
* As much as possible, we should try to reuse existing tables (e.g., for `<ExternalLexicalEntry>`, just add the new `<Sense>` or `<Form>` rows with the new lexicon specified, no need for anything special).
* Lexicons need to specify their extension somehow. For this, a separate table is best, because it can have 4 columns: extension lexicon rowid (foreign key), base lexicon id (text), base lexicon version (text), base lexicon rowid (nullable foreign key). A UNIQUE constraint could ensure an extension only has 1 base lexicon, and this requirement could be lifted later if multiple bases ever become a thing.

**Comment by goodmami** [comment]
Unlike expand lexicons, extensions are near unusable without the base lexicon because external entities would not exist in the database, so there's nothing linking any additions. Instead of relaxing the SQL foreign key constraints, it's probably better to just ensure that the base lexicon is loaded before adding extensions. Similarly, removing a base lexicon will first remove the extensions, to avoid constraint violations.

**Comment by arademaker** [comment]
I am assuming the lexicon extension and expansion are the ones discussed in https://www.aclweb.org/anthology/2021.gwc-1.11/, am I right?

**Comment by goodmami** [comment]
@arademaker That's correct
